[한지훈] [공동] Global Floating Footer 컴포넌트 구현
wecode-bootcamp-korea/fullstack2-2nd-Linked-IT-frontend pull request #21
Opened 2021-10-25 17:32 UTC by JivenHan

# PR 체크리스트

### PR을 올렸다면 아래 사항은 반드시 지켜주세요.

- [x] PR 우측 Linked Issues에서 적절한 이슈 하나를 걸어두었습니다.
- [x] PR 우측 Labels에서 적절한 라벨을 부착하였습니다.
- [x] PR 우측 Projects에서 적절한 프로젝트를 할당하였습니다.
- [x] 본 PR을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] git rebase와 squash를 했고 커밋 수가 하나인 것을 확인 했습니다.

### 아래 사항까지 모두 체크되어야만 리뷰 요청 라벨을 달 수 있고, code review를 받을 수 있습니다.

- [x] 기능이 제대로 실행되는지 확인 하였습니다.
- [x] npm start로 구현한 화면 혹은 기능을 확인할 수 있습니다.
- [x] self-refactoring으로 wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.

### 아래 사항까지 모두 체크되어야만 merge가 될 수 있습니다.

- [ ] 코드 리뷰 사항을 모두 반영하였습니다.

> 마크다운에서 체크를 하기 위해서는 [x] 이렇게 수정하시면 됩니다. [x ], [ x ] 가 아니라 정확하게 [x]여야 합니다. 혹은 마우스 클릭으로 체크해주세요.

# 구현 화면

<img width="300" alt="스크린샷 2021-10-26 오전 2 33 44" src="https://user-images.githubusercontent.com/87740944/138742950-0da6708e-2fc9-4584-8c14-201efb3f6439.png">

(여기에 구현 화면 스크린샷을 첨부해주세요)

# 이슈 체크리스트

(여기에 이슈에서 계획한 상세 구현 사항들을 체크리스트로 만들어 구현할 때마다 체크해주세요.)

- [x] 팀 멤버 사진으로 만든 LinkedIT banner

## 기타 질문 및 특이 사항

- 푸터에 스타일드 파일이 하나 밖에 없어서 styles 폴더를 안만들었습니다...?

2021-10-25 23:34 UTC, k-cool approved these changes
아니 다들 왜케 성실하세요???... 첫날부터 거생 넘나 많았써용~~ 👍

2021-10-25 23:34 UTC, k-cool commented on src/components/Footer/FloatingFooter.js
> +      <FooterText>
아직 데이터베이스 없어서 그런걸 수도 있지만 저 1차 할 때는 네브,풋터에서 이정도 나열되면 위에 배열 선언해서 아니면 패치받아서 맵을 돌리시는거 같아서 언끕해봅니다앙!

2021-10-25 23:34 UTC, k-cool commented on src/components/Footer/FloatingFooter.js
> +      <FooterFooter>
푸터푸터

2021-10-25 23:34 UTC, k-cool commented on src/components/Footer/FloatingFooterStyled.js
> +import styled from 'styled-components';
저희 페이지 기본 배경색이 흰색이어서 컴포넌트 배경색을 다른색으로 해보면 어떨까요?? 아! 아직 theme color안정해지셔서 안하신거군뇨?!! 아닌가?!

2021-10-25 23:34 UTC, k-cool commented on src/components/Footer/FloatingFooterStyled.js
> +`;
이미지 모서리 둥글게 깎으면 더이뿔것 가타양!!ㅋㅋㅋ 
하지만 디자인은 개취이므로 무시하셔도 됩니다!!

2021-10-26 05:09 UTC, JivenHan commented on src/components/Footer/FloatingFooterStyled.js
> +`;
저도 그게 좋을 것 같아서 전체를 감싸는 div를 둥글게 깎아봤습니다.

2021-10-26 05:24 UTC, han0gu requested changes
수고하셨어요 지훈님 👍  리뷰 확인 부탁드립니다 😄

2021-10-26 05:24 UTC, han0gu commented on src/components/Footer/FloatingFooter.js
> +import { FooterImg, FooterText, FooterFooter } from './FloatingFooterStyled';
지훈님 저희 styled 파일 따로 분리하지 않는 방향으로 결정하였습니다 !
`FloatingFooter.js` 파일 내에 같이 작성해주시면 좋을 것 같아요 😃

2021-10-26 05:25 UTC, JivenHan commented on src/components/Footer/FloatingFooter.js
> +import { FooterImg, FooterText, FooterFooter } from './FloatingFooterStyled';
넵, 아직 어제 저녁에 푸쉬했던거라 오늘 수정했습니다!

2021-10-26 05:26 UTC, han0gu commented on src/components/Footer/FloatingFooter.js
> +import { FooterImg, FooterText, FooterFooter } from './FloatingFooterStyled';
감사합니다 approve로 변경하였습니다 👍

2021-10-26 05:26 UTC, han0gu approved these changes

2021-10-26 06:33 UTC, closed without merging